title: ImportantSelenium
description: Selenium Courses
template:
  repo: importantselenium-template
  name: importantselenium
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
